---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/dollarbu/dollarbullcompany-
    - /bin/cp -R %PROJECT_ROOT%/public/css /home3/dollarbu/public_html/
    - /bin/cp -R %PROJECT_ROOT%/public/js /home3/dollarbu/public_html/